services:
  roster-guardian:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4010:4010"  # Backend API
      - "3000:3000"  # Frontend
    environment:
      - NODE_ENV=production
      - PORT=4010
      - FRONTEND_PORT=3000
      # Add environment variables for API URLs
      - REACT_APP_API_URL=http://localhost:4010
      - API_BASE_URL=http://localhost:4010
    volumes:
      # Persist uploads with proper permissions
      - ./uploads:/app/backend/uploads:rw
      # Only mount the database file, not the entire db directory
      - ./data:/app/backend/data:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Add network configuration for better container communication
    networks:
      - roster-network

networks:
  roster-network:
    driver: bridge